### ISSUE TITLE
Schematic circuit diagram of the IR part 

### ISSUE THREAD

**Issue by peros550** [maximkulkin/esp-ir#2]
Hi Maxim, 

I wanted to ask you about the circuit diagram. I'm using the following schematic in regards to the IR part. 
![IR Circuit](https://user-images.githubusercontent.com/12878906/56665681-2e17c680-66b3-11e9-8990-aef52eeb6545.png)

Are you using the same or anything similar? Do you see any room for improvements or corrections?  

Thanks
Yiannis

**Comment by maximkulkin** [comment]
Pretty much. I'm also experimenting with not having a resistor for LED (R2 on your schematic), since power supply I plan to use can not output high currents anyways.

**Comment by peros550** [comment]
What about R1? Would you think a value around 220 Ohm would make any difference for better results ?

**Comment by maximkulkin** [comment]
Ok, here are calculations: IR diodes I plan to use have forward voltage of 1.3V and forward current 30mA. I plan to power it with 3.3V. So R2 value should be (3.3 - 1.3) / 0.03 = 66.67 Om, which corresponds to standard value of 68 Om.
PN2222 has collector current rating of 600mA, so it is fine there. For 30mA collector current transistor currnet gain is somewhere around 50-60 (assume 50), so base current should be 30 / 50 = 600uA. Since transistors usually have base emitter voltage drop of ~0.6V and drive voltage is 3.3V, R1 = (3.3 - 0.6) / 0.0006 = 4500 Om. You can take something around 3.3kOm and should be fine. I've used 1kOm resistor.

PS I'm not an electronics expert, but calculations seem to be correct

**Comment by peros550** [comment]
Thank you Maxim, once again 👍
